<?php

namespace RDuuke\Newbie\Controllers;

use MartynBiz\Slim3Controller\Controller;

use RDuuke\Newbie\Contracts\Controller\ResourceController;
use RDuuke\Newbie\Models\Users;

class UsersController extends Controller implements ResourceController
{

    /**
     * Method index receives GET request extends the interface controller.
     */
    public function index()
    {
        newFlashMessage('test', 'test', 'warning');
        $users = Users::all();

        return view('users\home', compact('users'));
    }

    /**
     * Edit method, receives numeric parameter.
     *
     * @param $id int
     */
    public function edit($id)
    {
        $user = Users::find($id);

        return view('users/edit', compact('user'));
    }

    /**
     * Show method, receives numeric parameter.
     *
     * @param $id
     */
    public function show($id)
    {
        echo $id;
    }

    public function create()
    {
        return view('users/create');
    }

    /**
     * Store method receives POST parameters.
     */
    public function store()
    {
        Users::create(self::getPost());

        return redirect('users');
    }

    /**
     * Update method, receives numeric parameter.
     * and receives POST parameters.
     *
     * @param $id
     */
    public function update($id)
    {
        $request = self::getPostObject();
        $user = Users::find($id);
        $user->email = $request->email;
        $user->name = $request->name;
        $user->save();

        return redirect('users/');
    }

    /**
     * Destroy method, receives numeric parameter.
     *
     * @param $id
     */
    public function destroy($id)
    {
        $user = Users::find($id);
        $user->delete();

        return redirect('users');
    }

    public function getPostObject()
    {
        return (object) parent::getPost(); // TODO: Change the autogenerated stub
    }
}
